language: java
jdk:
  - openjdk8

# Travis CI 서버의 Home
branches:
  only:
    - master
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.gradle"

script: "./gradlew clean build"

before_deploy:
  - zip -r springboot-webservice *
  - mkdir -p deploy
  - mv springboot-webservice.zip deploy/springboot-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: springboot-webservice-deploy-shson # S3 버킷
    region: ap-northeast-2 # 서울
    skip_cleanup: true
    acl: public_read
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      repo: sh-son/springboot-webservice
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: springboot-webservice-deploy-shson # S3 버킷
    key: springboot-webservice.zip # S3 버킷에 저장된 springboot-webservice.zip 파일을 EC2로 배포
    bundle_tpye: zip
    application: springboot-webservice # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: springboot-webservice-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2 # 서울
    wait-until-deployed: true
    on:
      repo: sh-son/springboot-webservice
      branch: master

# CI 실행 완료시 메일로 알람 (Slack)
notifications:
  slack:
    secure: OFpepuFTZC2bv/UMk3LPm9haZZsCUGBvoFS3JsluuO7I8z1zOBLWBytE1K48F0HC6C0UmauDLjvUUajBMEs9K0qkZYNliEwyr2qWchw2vvbyHxXio7WwQNZVtjE4Hb8eWp/gVeb/3q/0sj7fP5CVqOIZ7H6v3s23ww6PyOlp7Y8UqIw59j+0BmO8HmXDvYweXjX7lRMAuMrqFBtr0NlqGFgfV9uWqokxaRoBURGFnL1MYhbi7lSw/zftW8tTa8pMUnCXcrwUuzoDv/05iTDm3XsergqblZu+9YX23qa3pdLMYEPq83l+A24NxQaiyaVeiCEVAnIyB6iXn+ak2Zm438Xer9K6M7Ty60mffW4/ER+MIKlYPSmBJdeNoZvsD3OW7Cilt8vK7UGy8ex0noKLr4SQ592ds5eZOoduzwgP9pFq0Y93SeWAiPHtzSrx8GRqY/zm0iEg+43x41EotZ/eWVXJ/opgYq5B5C+lgXx1iFm0NBK/nmEJrCd3h4Xqe2NKciOdNrq/y7B8uhkCsrx1vq29Ti7RF6uKyYTcpR+K6GFWckl05u6NzEfLa8o8o8gTI5oReL7Rr8hwRv3TTzkDaIs7LGPZ27DOMKY2KQlMVLn3aS+/2vSNDhOmJiBFEFjQ7Snk5PrLbTy+IL4i4NOlzNm5gGvvsk2wQg5v55oxmwc=
